### PR TITLE
close tmpfile before renaming/moving

### LINKED ISSUE #5: `atomic_write` is broken on Windows
I amy trying to run project using `xcodeproj`, which uses `atomos`, on Windows. 
Unfortunately this fails with this error message in `atomic_write`:

```
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/atomos-0.1.2/lib/atomos.rb:23:in `rename': [!] Permission denied @ rb_file_s_rename - (C:/Users/Jan/AppData/Local/Temp/.atomos.project.pbxproj20180806-12188-1yujbo3, C:/Projects/Fastlane/fastlane-demo/ionic/FastlaneDemoIonic/platforms/ios/FastlaneDemoIonic.xcodeproj/project.pbxproj) (Errno::EACCES)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/atomos-0.1.2/lib/atomos.rb:23:in `block in atomic_write'
        from C:/Ruby24-x64/lib/ruby/2.4.0/tempfile.rb:295:in `open'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/atomos-0.1.2/lib/atomos.rb:16:in `atomic_write'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.9/lib/xcodeproj/project.rb:354:in `save'
        ...
```

Crashing code is triggered here:
https://github.com/CocoaPods/Xcodeproj/blob/c6c0dbb0f977367c32fceea514c372dc9f8ab13f/lib/xcodeproj/project.rb#L354-L362

Crashing code is this:
https://github.com/segiddins/atomos/blob/b3660fce9ab43ff05342a6d2e8633021238a5bcf/lib/atomos.rb#L23

(Original issue for this was at https://github.com/CocoaPods/Xcodeproj/issues/549 - now moved here as I actually have to get this working)

### PR DESCRIPTION
**Pull request by janpio**
See #5 for bug description.

Before:
```
C:\Users\Jan\Documents\atomos (master -> origin)
λ bundle exec rspec

Atomos
  has a version number
  #atomic_write
    raises when no contents or block is given
    raises when both contents and block are given
    writes (FAILED - 1)

Failures:

  1) Atomos#atomic_write writes
     Failure/Error: File.rename(tmpfile.path, dest)

     Errno::EACCES:
       Permission denied @ rb_file_s_rename - (C:/Users/Jan/AppData/Local/Temp/.atomos.target20180806-21832-1nm9tci, C:/Users/Jan/AppData/Local/Temp/d20180806-21832-odi5ri/target)
     # ./lib/atomos.rb:23:in `rename'
     # ./lib/atomos.rb:23:in `block in atomic_write'
     # ./lib/atomos.rb:16:in `atomic_write'
     # ./spec/atomos_spec.rb:26:in `block (3 levels) in <top (required)>'

Finished in 0.03798 seconds (files took 0.37877 seconds to load)
4 examples, 1 failure

Failed examples:

rspec ./spec/atomos_spec.rb:25 # Atomos#atomic_write writes
```

After
```
C:\Users\Jan\Documents\atomos (master -> origin)
λ bundle exec rspec

Atomos
  has a version number
  #atomic_write
    raises when no contents or block is given
    raises when both contents and block are given
    writes

Finished in 0.45133 seconds (files took 3.1 seconds to load)
4 examples, 0 failures
```

fixes #5
helps with https://github.com/CocoaPods/Xcodeproj/issues/549

### CODE REVIEW

**Comment by janpio** [comment]
Unfortunately I don't have a Mac at hand and there is no CI setup for this repository.

File: lib/atomos.rb [hunk 1]
```diff
@@ -20,11 +21,14 @@ def atomic_write(dest, contents = nil, tmpdir: nil, &block)
         retval = yield tmpfile
       end
 
+      tmpfile.close
```
Comment (joshdholtz) [inline lib/atomos.rb]: May want to do this close in a begin/rescue/ensure to make sure it always gets closed in case of any 💥 that happen in the yield?

Comment (janpio) [reply lib/atomos.rb]: The file gets closed after the script ends anyway, it's only important that it's not open before the move, so I thought that might not be necessary. Correct?

Comment (joshdholtz) [reply lib/atomos.rb]: I don't know how this project/method gets used directly so I don't really know if its overkill or not but just something that caught my eye 🙃

Comment (janpio) [reply lib/atomos.rb]: Let's see what @segiddins says - I don't really know enough about ruby anyway 😕

**Comment by segiddins** [comment]
Thanks!
